---
- name: Deploy Redmine
  hosts: webservers
  become: true

  vars_files:
    - ../group_vars/webservers/vars.yml
    - ../group_vars/webservers/vault.yml

  roles:
    - datadog.datadog

  tasks:
    - name: Create env file
      template:
        src: templates/redmine.env.j2
        dest: /home/rudskiy/redmine.env

    - name: Run Redmine container
      community.docker.docker_container:
        name: redmine
        image: redmine
        state: started
        restart_policy: always
        ports:
          - "{{ redmine_port }}:3000"
        env_file: /home/rudskiy/redmine.env
